Avoid using `copy` package which requires pickling the structure, which won't work for un-materialized program value structures.
This would otherwise result in:

```
TypeError: cannot pickle 'coroutine' object
```

Removes unused method in test file.

PiperOrigin-RevId: 493868008